repos:
    - repo: local
      hooks:
        - id: black
          name: format python files
          entry: pipenv run black .
          language: system
          always_run: true
          pass_filenames: false
        - id: djhtml
          name: format django templates
          entry: pipenv run djhtml -t 4 templates
          language: system
          always_run: true
          pass_filenames: false
        - id: isort
          name: sort imports
          entry: pipenv run isort .
          language: system
          always_run: true
          pass_filenames: false
        - id: flake8
          name: flake8
          entry: pipenv run flake8
          language: system
          always_run: true
          pass_filenames: false
