# Generated by Django 3.1.4 on 2023-02-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20230223_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sections',
            field=models.ManyToManyField(blank=True, to='courses.Section'),
        ),
    ]
