# Generated by Django 3.1.4 on 2023-01-24 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0003_course_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="teachers",
            field=models.ManyToManyField(blank=True, related_name="teachers", to=settings.AUTH_USER_MODEL),
        ),
    ]
