# Generated by Django 3.1.4 on 2023-02-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_course_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_type", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(max_length=1200)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("task_files", models.FileField(blank=True, upload_to="")),
                ("members_can_attach_files", models.BooleanField(default=False)),
                ("members_attached_files", models.FileField(blank=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                ("tasks", models.ManyToManyField(to="courses.Task")),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="sections",
            field=models.ManyToManyField(to="courses.Section"),
        ),
    ]
