# Generated by Django 3.1.4 on 2023-02-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20230223_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(default='kek1'),
            preserve_default=False,
        ),
    ]
