# Generated by Django 3.1.4 on 2023-02-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_section_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="slug",
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
