# Generated by Django 4.2 on 2023-04-11 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0017_goal_alter_course_cover_course_goals"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="sections",
        ),
        migrations.AddField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="courses.course"
            ),
            preserve_default=False,
        ),
    ]
